name: Approve PR by Label

on:
  pull_request:
    types: [labeled]  # Trigger workflow when a label is added to the PR

jobs:
  approve_version_bump:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if the approved label is added
        id: check_label
        run: |
          echo "Label added: ${{ github.event.label.name }}"

      - name: Set PR status to success if the label is 'approved-for-merge'
        if: ${{ github.event.label.name == 'approved-for-merge' }}  # Correct condition syntax
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: "success",
              context: "version-bump-check",
              description: "Approved by adding the 'approved-for-merge' label",
            });
