name: Approve PR Version Bump

on:
  workflow_dispatch:  # This enables the manual trigger button

jobs:
  approve_version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set PR to approved
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.issue.number;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: "success",
              context: "version-bump-check",
              description: "Approved by maintainer",
            });
