name: Approve Version Bump

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]

jobs:
  check_reaction:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find the warning comment by the bot
        id: find_comment
        uses: actions/github-script@v6
        with:
          script: |
            const comments = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Find the warning comment made by the bot
            const warningComment = comments.data.find(comment =>
              comment.user.login === 'github-actions[bot]' && comment.body.includes('Warning: This PR will result in a new release')
            );

            if (warningComment) {
              return { comment_id: warningComment.id };
            } else {
              throw new Error('Warning comment not found.');
            }

      - name: Check if the comment has a thumbs up reaction
        id: check_reaction
        uses: actions/github-script@v6
        with:
          script: |
            const reactions = await github.reactions.listForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find_comment.outputs.comment_id }},
            });

            const thumbsUp = reactions.data.find(reaction => reaction.content === '+1');
            return { thumbs_up: thumbsUp ? 'true' : 'false' };

      - name: Extract maintainers from CODEOWNERS
        id: get_codeowners
        run: |
          # Extract the maintainers from CODEOWNERS file
          maintainers=$(grep -v '^#' CODEOWNERS | awk '{print $NF}' | sort | uniq)
          echo "maintainers=$maintainers" >> $GITHUB_ENV

      - name: Check if the reaction is from a maintainer
        if: steps.check_reaction.outputs.thumbs_up == 'true'
        id: check_maintainer
        run: |
          # Get the login of the person who added the thumbs-up reaction
          reaction_author="${{ github.event.comment.user.login }}"
          maintainers="${{ env.maintainers }}"

          # Convert maintainers string to array
          IFS=' ' read -r -a maintainers_array <<< "$maintainers"

          # Check if the reaction author is in the list of maintainers
          if [[ " ${maintainers_array[@]} " =~ " $reaction_author " ]]; then
            echo "Approval granted by maintainer: $reaction_author"
            echo "is_approved=true" >> $GITHUB_ENV
          else
            echo "Approval not granted by a maintainer"
            echo "is_approved=false" >> $GITHUB_ENV

      - name: Unblock PR if approved
        if: env.is_approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.issue.number;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: "success", # Mark the check as successful
              context: "version-bump-check",
              description: "Approved by maintainer",
            });
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
