name: Approve PR by Label

on:
  pull_request:
    types: [labeled]  # Trigger workflow when a label is added to the PR

jobs:
  approve_version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write  # Add this to explicitly grant write access to commit statuses

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if the approved label is added
        id: check_label
        run: |
          echo "Label added: ${{ github.event.label.name }}"

      - name: Set PR status to success if the label is 'approved-for-merge'
        if: ${{ github.event.label.name == 'approved-for-merge' }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "success",
              "context": "version-bump-check",
              "description": "Approved by adding the approved-for-merge label"
            }'
