name: Check for Version Bump in Chart.yaml

on:
  pull_request:

jobs:
  check_version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            deployments/chart/Chart.yaml

      - name: Extract Chart Version
        id: chart_version
        run: |
          version=$(yq e '.version' ./deployments/chart/Chart.yaml)
          echo "version=$version" >> $GITHUB_ENV

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "No tags found")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Compare and Set version bump status
        if: "v${{ env.version }} != ${{ env.latest_tag }}"
        run: echo "version_bump=true" >> $GITHUB_ENV

      - name: Post warning comment
        if: env.version_bump == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Warning: This PR will result in a new release because the version in Chart.yaml (`${{ env.version }}`) is different from the latest Git tag (`${{ env.latest_tag }}`). Please confirm before merging."

      - name: Set PR as blocked (requires approval)
        if: env.version_bump == 'true'
        uses: octodemo-resources/github-commit-status@v1.0.0
        with:
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          context: version-bump-check
          state: failure
          description: 'Version bump detected. Awaiting maintainer approval.'
          token: ${{ secrets.GITHUB_TOKEN }}

