name: Check for Version Bump in Chart.yaml

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  check_version_bump:
    name: Version Bump Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            deployments/chart/Chart.yaml

      - name: Extract Chart Version
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: chart_version
        run: |
          version=$(yq e '.version' ./deployments/chart/Chart.yaml)
          echo "version=$version" >> $GITHUB_ENV

      - name: Get latest Git tag
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Compare versions and fail if the PR version is greater than the latest tag
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        run: |
          chart_version=${{ env.version }}
          git_tag_version=${{ env.latest_tag }}

          # Strip the leading 'v' from the Git tag if it exists
          git_tag_version="${git_tag_version#v}"

          # Use sort -V to compare semantic versions (only works in bash)
          if [ "$(printf '%s\n' "$git_tag_version" "$chart_version" | sort -V | head -n1)" != "$git_tag_version" ]; then
            echo "Version bump detected: Chart version ($chart_version) is greater than the latest Git tag ($git_tag_version). Failing the job."
            exit 1
          else
            echo "No version bump detected or version in PR is not greater than the latest tag."
          fi

      - name: Post warning comment
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Warning: This PR will result in a new release because the version in Chart.yaml (`${{ env.version }}`) is greater than the latest Git tag (`${{ env.latest_tag }}`). Please confirm before merging."
