name: Check for Version Bump in Chart.yaml

on:
  pull_request:


jobs:
  check_version_bump:
    name: Version Bump Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            deployments/chart/Chart.yaml

      - name: Extract Chart Version
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: chart_version
        run: |
          version=$(yq e '.version' ./deployments/chart/Chart.yaml)
          echo "version=$version" >> $GITHUB_ENV

      - name: Get latest Git tag
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "No tags found")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Compare versions and fail if there is a version bump
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        run: |
          if [ "v${{ env.version }}" != "${{ env.latest_tag }}" ]; then
            echo "Version bump detected. Failing the job."
            exit 1
          else
            echo "No version bump detected."
          fi

      - name: Post warning comment
        if: ${{ failure() && !contains(github.event.pull_request.labels.*.name, 'approved-for-merge') }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Warning: This PR will result in a new release because the version in Chart.yaml (`${{ env.version }}`) is different from the latest Git tag (`${{ env.latest_tag }}`). Please confirm before merging."
