name: Check for Version Bump in Chart.yaml

on:
  pull_request:

jobs:
  check_version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            deployments/chart/Chart.yaml

      - name: Check if Chart.yaml has changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "Chart.yaml has been modified."

      - name: Extract version from Chart.yaml
        id: chart_version
        run: |
          version=$(yq e '.version' ./deployments/chart/Chart.yaml)
          echo "version=$version" >> $GITHUB_ENV
          echo "Extracted version from Chart.yaml: $version"

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          echo "Fetched latest Git tag: $latest_tag"

      - name: Debug versions (log both values)
        run: |
          echo "Version from Chart.yaml: ${{ env.version }}"
          echo "Latest Git tag: ${{ env.latest_tag }}"

      - name: Compare Chart version and latest Git tag
        run: |
          if [ "${{ env.version }}" != "${{ env.latest_tag }}" ]; then
            echo "Version bump detected: Chart version ( ${{ env.version }} ) differs from the latest Git tag ( ${{ env.latest_tag }} )."
            echo "version_bump=true" >> $GITHUB_ENV
          else
            echo "No version bump detected."
            echo "version_bump=false" >> $GITHUB_ENV

      - name: Post warning comment
        if: env.version_bump == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Warning: This PR will result in a new release because the version in Chart.yaml (`${{ env.version }}`) is different from the latest Git tag (`${{ env.latest_tag }}`). Please confirm before merging."

      - name: Set PR as blocked (requires thumbs up from maintainer)
        if: env.version_bump == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'failure',
              context: 'version-bump-check',
              description: 'Version bump detected. Awaiting maintainer approval.',
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
